SpaceshipAdventures:  Battle.o  BountyHunt.o Character.o CrewManager.o Enemies.o Gameship.o ListBattle.o main.o mainCharacter.o Manage.o Object.o UnfortunateEvents.o
	g++ Battle.o  BountyHunt.o Character.o CrewManager.o Enemies.o Gameship.o ListBattle.o main.o mainCharacter.o Manage.o Object.o  UnfortunateEvents.o -o SpaceshipAdventures

Battle.o: Battle.cpp
	g++ -c Battle.cpp

BountyHunt.o: BountyHunt.cpp
	g++ -c BountyHunt.cpp

Character.o: Character.cpp
	g++ -c Character.cpp

CrewManager.o: CrewManager.cpp
	g++ -c CrewManager.cpp

Enemies.o: Enemies.cpp
	g++ -c Enemies.cpp

Gameship.o: Gameship.cpp
	g++ -c Gameship.cpp

ListBattle.o: ListBattle.cpp
	g++ -c ListBattle.cpp

main.o: main.cpp
	g++ -c main.cpp

mainCharacter.o: mainCharacter.cpp
	g++ -c mainCharacter.cpp

Manage.o: Manage.cpp
	g++ -c Manage.cpp

Object.o: Object.cpp
	g++ -c Object.cpp

UnfortunateEvents.o: UnfortunateEvents.cpp
	g++ -c UnfortunateEvents.cpp

clean:
	rm *.o SpaceshipAdventures



